dist: xenial
sudo: false
language: cpp

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - cmake
      - cmake-data
      - lcov

install:
# (fake) install dependencies (usually involves wget, configure, make, ...)
# install into cache folder (build binaries+headers only, no sources and do NOT build there)
- mkdir -p $HOME/.cache
- touch $HOME/.cache/mydependency.so

script:
  - mkdir build && cd build
  # init coverage to 0 (optional)
  - lcov --directory . --zerocounters
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8
  - cmake -DCOVERAGE=1 ..
  - cmake --build . --config Debug -- -j $(nproc)
  - ./BestSequence

after_success:
# Create lcov report
# capture coverage info
- lcov --directory . --capture --output-file coverage.info
# filter out system and extra files.
# To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
- lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
# output coverage data for debugging (optional)
- lcov --list coverage.info
- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info


  #- coveralls -r .. --gcov-options '\-lp' -E ".*CMakeFiles.*"
