dist: bionic
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

before_install:
  - pip install --user cpp-coveralls

script:
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 
  - make

after_success:
  - coveralls --root .
