dist: xenial
sudo: false
language: cpp

cache:
  - cchache
  - apt
  - pip

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      #- g++-8
      - cmake

before_install:
  - pip install --user cpp-coveralls
  - gem install coveralls-lcov
  - sudo apt-get install cmake cmake-data
  - sudo apt-get install lcov

script:
  - mkdir build && cd build
  - cmake -DCOVERAGE=ON ..
  - make
  - ./BestSequence

after_success:
  - coveralls --root . -E ".*CMakeFiles.*"
