dist: xenial
sudo: false
language: cpp

cache:
  - cchache
  - apt
  - pip

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - cmake

before_install:
  - pip install --user cpp-coveralls
  - gem install coveralls-lcov
  - sudo apt-get install cmake-data
  - sudo apt-get install lcov

script:
  - mkdir build && cd build
  # init coverage to 0 (optional)
  - lcov --directory . --zerocounters
  - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8
  - cmake -DCOVERAGE=ON ..
  - make
  - ./BestSequence

after_success:
- lcov --directory . --capture --output-file coverage.info
- lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
- lcov --list coverage.info
- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info


  #- coveralls -r .. --gcov-options '\-lp' -E ".*CMakeFiles.*"
